merge1: 
	gcc -o teste main.c item.h merge1.c

merge2: 
	gcc -o teste main.c item.h merge2.c

merge3: 
	gcc -o teste main.c item.h merge3.c

merge4: 
	gcc -o teste main.c item.h merge4.c

merge5: 
	gcc -o teste main.c item.h merge5.c

merge6: 
	gcc -o teste main.c item.h merge6.c

merge7: 
	gcc -o teste main.c item.h merge7.c