bubble_sort:
	gcc -o teste main.c item.h bubble_sort.c

insertion_sort:
	gcc -o teste main.c item.h insertion_sort.c

selection_sort:
	gcc -o teste main.c item.h selection_sort.c

shaker_sort:
	gcc -o teste main.c item.h shaker_sort.c